[package]
name = "athenaeum"
version = "0.1.0"
authors = ["Senyo <simpsonsenyo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
handlebars = "3.5.1"
structopt = "0.3.21"
anyhow = "1.0.36"
